import type { Recipe } from '../components/RecipePanel';

// Mock recipe data organized by cuisine
export const mockRecipesByCuisine: Record<string, Recipe[]> = {
  'Italian': [
    {
      id: 'mock-101',
      title: 'Authentic Pasta Carbonara',
      country: 'Italy',
      region: 'Europe',
      prepTime: '25 mins',
      image: 'https://images.unsplash.com/photo-1612874742237-6526221588f3?w=500&q=80',
      isFavorite: false,
      description: 'Classic Roman pasta dish with eggs, cheese, pancetta, and black pepper.',
      coordinates: [41.9028, 12.4964], // Rome coordinates
      ingredients: ['200g spaghetti', '100g pancetta', '2 large eggs', '50g pecorino cheese', 'Black pepper'],
      instructions: ['Cook pasta until al dente', 'Fry pancetta until crispy', 'Mix eggs and cheese in a bowl', 'Combine everything while pasta is hot'],
      dietaryTags: ['high-protein'],
    },
    {
      id: 'mock-102',
      title: 'Margherita Pizza',
      country: 'Italy',
      region: 'Europe',
      prepTime: '45 mins',
      image: 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=500&q=80',
      isFavorite: false,
      description: 'Simple pizza with tomatoes, mozzarella, basil, and olive oil.',
      coordinates: [40.8518, 14.2681], // Naples coordinates
      ingredients: ['Pizza dough', 'San Marzano tomatoes', 'Fresh mozzarella', 'Basil', 'Olive oil', 'Salt'],
      instructions: ['Stretch dough', 'Add tomato sauce', 'Top with cheese', 'Bake', 'Add basil'],
      dietaryTags: ['vegetarian'],
    },
    {
      id: 'mock-103',
      title: 'Risotto alla Milanese',
      country: 'Italy',
      region: 'Europe',
      prepTime: '40 mins',
      image: 'https://images.unsplash.com/photo-1633964913849-96bb09049e17?w=500&q=80',
      isFavorite: false,
      description: 'Creamy saffron risotto from Milan.',
      coordinates: [45.4642, 9.1900], // Milan coordinates
      ingredients: ['Arborio rice', 'Saffron', 'Butter', 'Parmesan cheese', 'Onion', 'Chicken broth'],
      instructions: ['Sauté onion', 'Add rice', 'Add saffron broth gradually', 'Stir until creamy', 'Add Parmesan'],
      dietaryTags: ['vegetarian', 'gluten-free'],
    },
    {
      id: 'mock-104',
      title: 'Lasagna alla Bolognese',
      country: 'Italy',
      region: 'Europe',
      prepTime: '1 hr 30 mins',
      image: 'https://images.unsplash.com/photo-1619895092538-128341789043?w=500&q=80',
      isFavorite: false,
      description: 'Layered pasta with meat sauce and béchamel.',
      coordinates: [44.4949, 11.3426], // Bologna coordinates
      ingredients: ['Lasagna noodles', 'Ground beef', 'Tomato sauce', 'Béchamel', 'Parmesan'],
      instructions: ['Cook meat sauce', 'Layer noodles, sauce, béchamel', 'Bake'],
      dietaryTags: [],
    },
    {
      id: 'mock-105',
      title: 'Tiramisu',
      country: 'Italy',
      region: 'Europe',
      prepTime: '30 mins',
      image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=500&q=80',
      isFavorite: false,
      description: 'Coffee-flavored dessert with mascarpone and ladyfingers.',
      coordinates: [45.4384, 10.9916], // Verona coordinates
      ingredients: ['Ladyfingers', 'Espresso', 'Mascarpone', 'Eggs', 'Sugar', 'Cocoa powder'],
      instructions: ['Dip ladyfingers in espresso', 'Layer with mascarpone mixture', 'Dust with cocoa', 'Chill'],
      dietaryTags: ['vegetarian'],
    },
    {
      id: 'mock-106',
      title: 'Osso Buco',
      country: 'Italy',
      region: 'Europe',
      prepTime: '2 hrs',
      image: 'https://images.unsplash.com/photo-1609770424775-39de3518ae11?w=500&q=80',
      isFavorite: false,
      description: 'Braised veal shanks with vegetables and wine.',
      coordinates: [45.4642, 9.1900], // Milan coordinates
      ingredients: ['Veal shanks', 'Carrots', 'Onion', 'Celery', 'White wine', 'Tomato paste'],
      instructions: ['Brown meat', 'Add vegetables', 'Deglaze with wine', 'Simmer'],
      dietaryTags: ['gluten-free'],
    },
    {
      id: 'mock-107',
      title: 'Panzanella Salad',
      country: 'Italy',
      region: 'Europe',
      prepTime: '20 mins',
      image: 'https://images.unsplash.com/photo-1592417817098-8fd3d9eb14a5?w=500&q=80',
      isFavorite: false,
      description: 'Tuscan bread salad with tomatoes and cucumbers.',
      coordinates: [43.7696, 11.2558], // Florence coordinates
      ingredients: ['Stale bread', 'Tomatoes', 'Cucumber', 'Red onion', 'Basil', 'Olive oil', 'Vinegar'],
      instructions: ['Soak bread', 'Mix with veggies', 'Dress with oil and vinegar'],
      dietaryTags: ['vegan'],
    },
    {
      id: 'mock-108',
      title: 'Eggplant Parmigiana',
      country: 'Italy',
      region: 'Europe',
      prepTime: '1 hr',
      image: 'https://images.unsplash.com/photo-1625937329935-287441889bce?w=500&q=80',
      isFavorite: false,
      description: 'Baked eggplant with tomato sauce and cheese.',
      coordinates: [40.8518, 14.2681], // Naples coordinates
      ingredients: ['Eggplant', 'Tomato sauce', 'Mozzarella', 'Parmesan', 'Basil'],
      instructions: ['Fry eggplant', 'Layer with sauce and cheese', 'Bake'],
      dietaryTags: ['vegetarian'],
    },
    {
      id: 'mock-109',
      title: 'Minestrone Soup',
      country: 'Italy',
      region: 'Europe',
      prepTime: '50 mins',
      image: 'https://images.unsplash.com/photo-1614469723922-c043ad9fd036?w=500&q=80',
      isFavorite: false,
      description: 'Hearty vegetable soup with beans and pasta.',
      coordinates: [44.4949, 11.3426], // Bologna coordinates
      ingredients: ['Mixed vegetables', 'Beans', 'Pasta', 'Tomato', 'Broth', 'Herbs'],
      instructions: ['Sauté veggies', 'Add broth and beans', 'Simmer', 'Add pasta'],
      dietaryTags: ['vegan'],
    },
    {
      id: 'mock-110',
      title: 'Focaccia Bread',
      country: 'Italy',
      region: 'Europe',
      prepTime: '2 hrs',
      image: 'https://images.unsplash.com/photo-1600628421055-4d30de868b8f?w=500&q=80',
      isFavorite: false,
      description: 'Flat oven-baked bread with olive oil and herbs.',
      coordinates: [44.4056, 8.9463], // Genoa coordinates
      ingredients: ['Flour', 'Yeast', 'Olive oil', 'Rosemary', 'Salt'],
      instructions: ['Mix dough', 'Let rise', 'Top with oil and herbs', 'Bake'],
      dietaryTags: ['vegan'],
    },
  ],
  'Mexican': [
    {
      id: 'mock-201',
      title: 'Authentic Guacamole',
      country: 'Mexico',
      region: 'North America',
      prepTime: '15 mins',
      image: 'https://images.unsplash.com/photo-1574179226842-0b9ebb3eb591?w=500&q=80',
      isFavorite: false,
      description: 'Traditional avocado dip with lime, onion, and cilantro.',
      coordinates: [19.4326, -99.1332], // Mexico City coordinates
      ingredients: ['2 ripe avocados', '1 lime', '1/2 onion', 'Cilantro', 'Salt'],
      instructions: ['Mash avocados', 'Add lime juice', 'Mix in chopped onion and cilantro', 'Season with salt'],
      dietaryTags: ['vegan', 'gluten-free'],
    },
    {
      id: 'mock-202',
      title: 'Tacos al Pastor',
      country: 'Mexico',
      region: 'North America',
      prepTime: '1 hr',
      image: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=500&q=80',
      isFavorite: false,
      description: 'Marinated pork tacos with pineapple and onion.',
      coordinates: [19.4326, -99.1332], // Mexico City coordinates
      ingredients: ['Pork shoulder', 'Achiote paste', 'Pineapple', 'Onion', 'Corn tortillas'],
      instructions: ['Marinate pork', 'Grill', 'Slice thin', 'Serve on tortillas with pineapple'],
      dietaryTags: [],
    },
    {
      id: 'mock-203',
      title: 'Chiles en Nogada',
      country: 'Mexico',
      region: 'North America',
      prepTime: '1 hr 30 mins',
      image: 'https://images.unsplash.com/photo-1624300629298-e9de39c13be5?w=500&q=80',
      isFavorite: false,
      description: 'Stuffed poblano peppers with walnut sauce.',
      coordinates: [19.0414, -98.2063], // Puebla coordinates
      ingredients: ['Poblano peppers', 'Ground beef', 'Fruits', 'Walnuts', 'Cream', 'Pomegranate'],
      instructions: ['Stuff peppers', 'Prepare walnut sauce', 'Top with sauce and pomegranate'],
      dietaryTags: [],
    },
    {
      id: 'mock-204',
      title: 'Mole Poblano',
      country: 'Mexico',
      region: 'North America',
      prepTime: '2 hrs',
      image: 'https://images.unsplash.com/photo-1625166913168-9a1f72a1edfb?w=500&q=80',
      isFavorite: false,
      description: 'Rich sauce with chocolate and spices over chicken.',
      coordinates: [19.0414, -98.2063], // Puebla coordinates
      ingredients: ['Chicken', 'Mole paste', 'Chocolate', 'Spices', 'Broth'],
      instructions: ['Cook chicken', 'Prepare mole', 'Combine and simmer'],
      dietaryTags: [],
    },
    {
      id: 'mock-205',
      title: 'Pozole Rojo',
      country: 'Mexico',
      region: 'North America',
      prepTime: '2 hrs',
      image: 'https://images.unsplash.com/photo-1582234372722-50d7ccc30ebd?w=500&q=80',
      isFavorite: false,
      description: 'Hominy soup with pork and red chiles.',
      coordinates: [19.4326, -99.1332], // Mexico City coordinates
      ingredients: ['Pork shoulder', 'Hominy', 'Red chiles', 'Onion', 'Garlic'],
      instructions: ['Cook pork', 'Add hominy and chiles', 'Simmer'],
      dietaryTags: ['gluten-free'],
    },
    {
      id: 'mock-206',
      title: 'Enchiladas Verdes',
      country: 'Mexico',
      region: 'North America',
      prepTime: '45 mins',
      image: 'https://images.unsplash.com/photo-1548108126-b8963d99d73f?w=500&q=80',
      isFavorite: false,
      description: 'Tortillas with chicken and green tomatillo sauce.',
      coordinates: [19.4326, -99.1332], // Mexico City coordinates
      ingredients: ['Tortillas', 'Chicken', 'Tomatillos', 'Green chiles', 'Cream'],
      instructions: ['Make sauce', 'Fill tortillas', 'Bake with sauce and cheese'],
      dietaryTags: [],
    },
    {
      id: 'mock-207',
      title: 'Sopa de Lima',
      country: 'Mexico',
      region: 'North America',
      prepTime: '1 hr',
      image: 'https://images.unsplash.com/photo-1594606909008-f8311f201fae?w=500&q=80',
      isFavorite: false,
      description: 'Yucatecan lime soup with chicken and tortilla strips.',
      coordinates: [21.1619, -86.8515], // Cancun coordinates
      ingredients: ['Chicken', 'Lime', 'Tortilla strips', 'Tomato', 'Onion'],
      instructions: ['Cook chicken', 'Add veggies and lime', 'Serve with tortilla strips'],
      dietaryTags: ['gluten-free'],
    },
    {
      id: 'mock-208',
      title: 'Tamales',
      country: 'Mexico',
      region: 'North America',
      prepTime: '2 hrs',
      image: 'https://images.unsplash.com/photo-1611525449997-8697640705ef?w=500&q=80',
      isFavorite: false,
      description: 'Steamed masa dough with fillings in corn husks.',
      coordinates: [19.4326, -99.1332], // Mexico City coordinates
      ingredients: ['Masa harina', 'Lard', 'Chicken or pork', 'Corn husks', 'Salsa'],
      instructions: ['Prepare dough', 'Fill and wrap', 'Steam'],
      dietaryTags: ['gluten-free'],
    },
    {
      id: 'mock-209',
      title: 'Elote (Mexican Street Corn)',
      country: 'Mexico',
      region: 'North America',
      prepTime: '20 mins',
      image: 'https://images.unsplash.com/photo-1582169296194-e4d644c48063?w=500&q=80',
      isFavorite: false,
      description: 'Grilled corn with mayo, cheese, and chili.',
      coordinates: [19.4326, -99.1332], // Mexico City coordinates
      ingredients: ['Corn', 'Mayonnaise', 'Cotija cheese', 'Chili powder', 'Lime'],
      instructions: ['Grill corn', 'Spread with mayo', 'Sprinkle cheese and chili', 'Squeeze lime'],
      dietaryTags: ['vegetarian'],
    },
    {
      id: 'mock-210',
      title: 'Ceviche',
      country: 'Mexico',
      region: 'North America',
      prepTime: '30 mins',
      image: 'https://images.unsplash.com/photo-1604544203292-0d06d6a1d98f?w=500&q=80',
      isFavorite: false,
      description: 'Raw fish cured in lime juice with tomatoes and cilantro.',
      coordinates: [20.6597, -103.3496], // Guadalajara coordinates
      ingredients: ['White fish', 'Lime juice', 'Tomato', 'Onion', 'Cilantro'],
      instructions: ['Marinate fish in lime', 'Mix with veggies', 'Serve chilled'],
      dietaryTags: ['gluten-free'],
    }
  ],
  'Chinese': [
    {
      id: 'mock-301',
      title: 'Kung Pao Chicken',
      country: 'China',
      region: 'Asia',
      prepTime: '30 mins',
      image: 'https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?w=500&q=80',
      isFavorite: false,
      description: 'Spicy stir-fried chicken with peanuts and vegetables.',
      coordinates: [31.2304, 121.4737], // Shanghai coordinates
      ingredients: ['Chicken breast', 'Peanuts', 'Dried chilies', 'Bell pepper', 'Soy sauce'],
      instructions: ['Stir-fry chicken', 'Add vegetables', 'Add sauce and peanuts', 'Serve'],
      dietaryTags: [],
    },
    {
      id: 'mock-302',
      title: 'Mapo Tofu',
      country: 'China',
      region: 'Asia',
      prepTime: '25 mins',
      image: 'https://images.unsplash.com/photo-1582234372722-50d7ccc30ebd?w=500&q=80',
      isFavorite: false,
      description: 'Sichuan tofu with minced pork in spicy sauce.',
      coordinates: [30.5728, 104.0668], // Chengdu coordinates
      ingredients: ['Tofu', 'Ground pork', 'Doubanjiang', 'Sichuan peppercorn', 'Green onion'],
      instructions: ['Cook pork', 'Add tofu and sauce', 'Simmer', 'Garnish with green onion'],
      dietaryTags: ['gluten-free'],
    },
    {
      id: 'mock-303',
      title: 'Sweet and Sour Pork',
      country: 'China',
      region: 'Asia',
      prepTime: '40 mins',
      image: 'https://images.unsplash.com/photo-1625938145744-34be14759eda?w=500&q=80',
      isFavorite: false,
      description: 'Crispy pork in tangy sweet and sour sauce.',
      coordinates: [31.2304, 121.4737], // Shanghai coordinates
      ingredients: ['Pork loin', 'Pineapple', 'Bell pepper', 'Vinegar', 'Sugar'],
      instructions: ['Fry pork', 'Stir-fry veggies', 'Add sauce', 'Combine all'],
      dietaryTags: [],
    },
    {
      id: 'mock-304',
      title: 'Xiaolongbao (Soup Dumplings)',
      country: 'China',
      region: 'Asia',
      prepTime: '2 hrs',
      image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=500&q=80',
      isFavorite: false,
      description: 'Steamed dumplings filled with meat and broth.',
      coordinates: [31.2304, 121.4737], // Shanghai coordinates
      ingredients: ['Dumpling wrappers', 'Pork', 'Gelatinized broth', 'Ginger', 'Soy sauce'],
      instructions: ['Make filling', 'Wrap dumplings', 'Steam'],
      dietaryTags: [],
    },
    {
      id: 'mock-305',
      title: 'Peking Duck',
      country: 'China',
      region: 'Asia',
      prepTime: '3 hrs',
      image: 'https://images.unsplash.com/photo-1518985584237-583f55638fcf?w=500&q=80',
      isFavorite: false,
      description: 'Crispy roasted duck served with pancakes and hoisin.',
      coordinates: [39.9042, 116.4074], // Beijing coordinates
      ingredients: ['Duck', 'Hoisin sauce', 'Cucumber', 'Scallion', 'Pancakes'],
      instructions: ['Roast duck', 'Slice', 'Serve with pancakes and toppings'],
      dietaryTags: [],
    },
    {
      id: 'mock-306',
      title: 'Char Siu (BBQ Pork)',
      country: 'China',
      region: 'Asia',
      prepTime: '2 hrs',
      image: 'https://images.unsplash.com/photo-1562967916-eb82221dfb92?w=500&q=80',
      isFavorite: false,
      description: 'Cantonese roasted pork with sweet glaze.',
      coordinates: [22.3193, 114.1694], // Hong Kong coordinates
      ingredients: ['Pork shoulder', 'Char siu sauce', 'Honey', 'Soy sauce'],
      instructions: ['Marinate pork', 'Roast', 'Glaze with honey'],
      dietaryTags: [],
    },
    {
      id: 'mock-307',
      title: 'Hot and Sour Soup',
      country: 'China',
      region: 'Asia',
      prepTime: '35 mins',
      image: 'https://images.unsplash.com/photo-1589674781759-c21c37956a44?w=500&q=80',
      isFavorite: false,
      description: 'Spicy, tangy soup with tofu and mushrooms.',
      coordinates: [39.9042, 116.4074], // Beijing coordinates
      ingredients: ['Tofu', 'Mushrooms', 'Egg', 'Vinegar', 'White pepper'],
      instructions: ['Simmer broth', 'Add ingredients', 'Thicken', 'Season'],
      dietaryTags: ['vegetarian'],
    },
    {
      id: 'mock-308',
      title: 'Dan Dan Noodles',
      country: 'China',
      region: 'Asia',
      prepTime: '30 mins',
      image: 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?w=500&q=80',
      isFavorite: false,
      description: 'Spicy Sichuan noodles with pork and preserved veggies.',
      coordinates: [30.5728, 104.0668], // Chengdu coordinates
      ingredients: ['Noodles', 'Ground pork', 'Sichuan pepper', 'Preserved vegetables', 'Chili oil'],
      instructions: ['Cook noodles', 'Prepare topping', 'Assemble and serve'],
      dietaryTags: [],
    },
    {
      id: 'mock-309',
      title: 'Scallion Pancakes',
      country: 'China',
      region: 'Asia',
      prepTime: '50 mins',
      image: 'https://images.unsplash.com/photo-1549411119-e8f412aed286?w=500&q=80',
      isFavorite: false,
      description: 'Flaky pan-fried pancakes with scallions.',
      coordinates: [31.2304, 121.4737], // Shanghai coordinates
      ingredients: ['Flour', 'Scallions', 'Oil', 'Salt'],
      instructions: ['Make dough', 'Roll with scallions', 'Pan-fry'],
      dietaryTags: ['vegan'],
    },
    {
      id: 'mock-310',
      title: 'Egg Fried Rice',
      country: 'China',
      region: 'Asia',
      prepTime: '20 mins',
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=500&q=80',
      isFavorite: false,
      description: 'Stir-fried rice with eggs and vegetables.',
      coordinates: [31.2304, 121.4737], // Shanghai coordinates
      ingredients: ['Cooked rice', 'Eggs', 'Peas', 'Carrot', 'Soy sauce'],
      instructions: ['Scramble eggs', 'Add rice and veggies', 'Stir-fry', 'Season'],
      dietaryTags: ['vegetarian'],
    }
  ],
  'Indian': [
    {
      id: 'mock-401',
      title: 'Butter Chicken',
      country: 'India',
      region: 'Asia',
      prepTime: '50 mins',
      image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=500&q=80',
      isFavorite: false,
      description: 'Creamy tomato-based chicken curry.',
      coordinates: [28.6139, 77.2090], // Delhi coordinates
      ingredients: ['Chicken', 'Tomato puree', 'Cream', 'Butter', 'Spices'],
      instructions: ['Cook chicken', 'Prepare sauce', 'Combine and simmer'],
      dietaryTags: [],
    },
    {
      id: 'mock-402',
      title: 'Chana Masala',
      country: 'India',
      region: 'Asia',
      prepTime: '40 mins',
      image: 'https://images.unsplash.com/photo-1585937421612-70a008356c36?w=500&q=80',
      isFavorite: false,
      description: 'Spiced chickpea curry.',
      coordinates: [28.6139, 77.2090], // Delhi coordinates
      ingredients: ['Chickpeas', 'Onion', 'Tomato', 'Spices', 'Cilantro'],
      instructions: ['Sauté onion', 'Add spices', 'Simmer with chickpeas'],
      dietaryTags: ['vegan'],
    },
    {
      id: 'mock-403',
      title: 'Rogan Josh',
      country: 'India',
      region: 'Asia',
      prepTime: '1 hr 30 mins',
      image: 'https://images.unsplash.com/photo-1593001872095-7d5b3868dd2b?w=500&q=80',
      isFavorite: false,
      description: 'Kashmiri lamb curry with aromatic spices.',
      coordinates: [34.0837, 74.7973], // Srinagar coordinates
      ingredients: ['Lamb', 'Yogurt', 'Spices', 'Onion', 'Ginger'],
      instructions: ['Brown lamb', 'Add spices', 'Simmer with yogurt'],
      dietaryTags: ['gluten-free'],
    },
    {
      id: 'mock-404',
      title: 'Palak Paneer',
      country: 'India',
      region: 'Asia',
      prepTime: '35 mins',
      image: 'https://images.unsplash.com/photo-1596452932476-7461afc5069d?w=500&q=80',
      isFavorite: false,
      description: 'Spinach and cottage cheese curry.',
      coordinates: [28.6139, 77.2090], // Delhi coordinates
      ingredients: ['Spinach', 'Paneer', 'Onion', 'Tomato', 'Spices'],
      instructions: ['Blanch spinach', 'Blend', 'Cook with paneer and spices'],
      dietaryTags: ['vegetarian'],
    },
    {
      id: 'mock-405',
      title: 'Dosa with Sambar',
      country: 'India',
      region: 'Asia',
      prepTime: '1 hr',
      image: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?w=500&q=80',
      isFavorite: false,
      description: 'Crispy rice crepes with lentil stew.',
      coordinates: [13.0827, 80.2707], // Chennai coordinates
      ingredients: ['Rice', 'Urad dal', 'Potato', 'Sambar spices'],
      instructions: ['Ferment batter', 'Cook dosa', 'Serve with sambar'],
      dietaryTags: ['vegan'],
    },
    {
      id: 'mock-406',
      title: 'Biryani',
      country: 'India',
      region: 'Asia',
      prepTime: '1 hr 30 mins',
      image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500&q=80',
      isFavorite: false,
      description: 'Fragrant rice with meat or vegetables and spices.',
      coordinates: [17.3850, 78.4867], // Hyderabad coordinates
      ingredients: ['Basmati rice', 'Chicken or vegetables', 'Yogurt', 'Spices'],
      instructions: ['Layer rice and filling', 'Cook with steam'],
      dietaryTags: [],
    },
    {
      id: 'mock-407',
      title: 'Tandoori Chicken',
      country: 'India',
      region: 'Asia',
      prepTime: '1 hr',
      image: 'https://images.unsplash.com/photo-1610057099431-d73a1c9d2f2f?w=500&q=80',
      isFavorite: false,
      description: 'Yogurt-marinated grilled chicken.',
      coordinates: [28.6139, 77.2090], // Delhi coordinates
      ingredients: ['Chicken', 'Yogurt', 'Spices', 'Lemon juice'],
      instructions: ['Marinate chicken', 'Grill or bake'],
      dietaryTags: ['gluten-free'],
    },
    {
      id: 'mock-408',
      title: 'Aloo Gobi',
      country: 'India',
      region: 'Asia',
      prepTime: '30 mins',
      image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=500&q=80',
      isFavorite: false,
      description: 'Potato and cauliflower curry.',
      coordinates: [28.6139, 77.2090], // Delhi coordinates
      ingredients: ['Potato', 'Cauliflower', 'Onion', 'Spices'],
      instructions: ['Sauté veggies', 'Add spices', 'Cook until tender'],
      dietaryTags: ['vegan'],
    },
    {
      id: 'mock-409',
      title: 'Lamb Vindaloo',
      country: 'India',
      region: 'Asia',
      prepTime: '1 hr 20 mins',
      image: 'https://images.unsplash.com/photo-1588761454708-533e3255a5b8?w=500&q=80',
      isFavorite: false,
      description: 'Spicy Goan lamb curry.',
      coordinates: [15.2993, 74.1240], // Goa coordinates
      ingredients: ['Lamb', 'Vinegar', 'Spices', 'Onion', 'Garlic'],
      instructions: ['Marinate lamb', 'Cook with spices', 'Simmer'],
      dietaryTags: ['gluten-free'],
    },
    {
      id: 'mock-410',
      title: 'Gulab Jamun',
      country: 'India',
      region: 'Asia',
      prepTime: '45 mins',
      image: 'https://images.unsplash.com/photo-1627823608441-dd96538742f3?w=500&q=80',
      isFavorite: false,
      description: 'Fried milk balls in sugar syrup.',
      coordinates: [28.6139, 77.2090], // Delhi coordinates
      ingredients: ['Milk powder', 'Flour', 'Sugar', 'Cardamom', 'Rose water'],
      instructions: ['Make dough', 'Fry balls', 'Soak in syrup'],
      dietaryTags: ['vegetarian'],
    }
  ],
  'Japanese': [
    {
      id: 'mock-501',
      title: 'Authentic Sushi Rolls',
      country: 'Japan',
      region: 'Asia',
      prepTime: '1 hr',
      image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=500&q=80',
      isFavorite: false,
      description: 'Rice and seafood rolled in nori seaweed.',
      coordinates: [35.6895, 139.6917], // Tokyo coordinates
      ingredients: ['Sushi rice', 'Nori', 'Fresh fish', 'Wasabi', 'Soy sauce'],
      instructions: ['Prepare rice', 'Slice fish', 'Roll with nori', 'Slice', 'Serve with wasabi and soy'],
      dietaryTags: ['gluten-free'],
    },
    {
      id: 'mock-502',
      title: 'Ramen',
      country: 'Japan',
      region: 'Asia',
      prepTime: '2 hrs',
      image: 'https://images.unsplash.com/photo-1557872943-16a5ac26437e?w=500&q=80',
      isFavorite: false,
      description: 'Noodle soup with pork, egg, and vegetables.',
      coordinates: [43.0667, 141.3500], // Sapporo coordinates
      ingredients: ['Ramen noodles', 'Pork belly', 'Egg', 'Miso or soy broth', 'Green onion'],
      instructions: ['Prepare broth', 'Cook noodles', 'Assemble with toppings'],
      dietaryTags: [],
    },
    {
      id: 'mock-503',
      title: 'Tempura',
      country: 'Japan',
      region: 'Asia',
      prepTime: '45 mins',
      image: 'https://images.unsplash.com/photo-1619266465172-02a857c3556d?w=500&q=80',
      isFavorite: false,
      description: 'Lightly battered and fried seafood and vegetables.',
      coordinates: [34.6937, 135.5023], // Osaka coordinates
      ingredients: ['Shrimp', 'Sweet potato', 'Eggplant', 'Tempura flour', 'Oil'],
      instructions: ['Prepare batter', 'Dip ingredients', 'Fry until golden'],
      dietaryTags: [],
    },
    {
      id: 'mock-504',
      title: 'Okonomiyaki',
      country: 'Japan',
      region: 'Asia',
      prepTime: '40 mins',
      image: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=500&q=80',
      isFavorite: false,
      description: 'Savory cabbage pancake with toppings.',
      coordinates: [34.6937, 135.5023], // Osaka coordinates
      ingredients: ['Cabbage', 'Flour', 'Egg', 'Pork belly', 'Okonomiyaki sauce'],
      instructions: ['Mix batter', 'Cook on griddle', 'Add toppings'],
      dietaryTags: [],
    },
    {
      id: 'mock-505',
      title: 'Tonkatsu',
      country: 'Japan',
      region: 'Asia',
      prepTime: '35 mins',
      image: 'https://images.unsplash.com/photo-1604909052743-94e838986d24?w=500&q=80',
      isFavorite: false,
      description: 'Breaded and deep-fried pork cutlet.',
      coordinates: [35.6895, 139.6917], // Tokyo coordinates
      ingredients: ['Pork cutlet', 'Panko breadcrumbs', 'Egg', 'Flour', 'Cabbage'],
      instructions: ['Bread pork', 'Fry', 'Serve with cabbage and sauce'],
      dietaryTags: [],
    },
    {
      id: 'mock-506',
      title: 'Yakitori',
      country: 'Japan',
      region: 'Asia',
      prepTime: '30 mins',
      image: 'https://images.unsplash.com/photo-1555126634-323283e090fa?w=500&q=80',
      isFavorite: false,
      description: 'Grilled chicken skewers with tare sauce.',
      coordinates: [35.6895, 139.6917], // Tokyo coordinates
      ingredients: ['Chicken', 'Leek', 'Soy sauce', 'Mirin', 'Sugar'],
      instructions: ['Skewer chicken', 'Grill', 'Brush with sauce'],
      dietaryTags: ['gluten-free'],
    },
    {
      id: 'mock-507',
      title: 'Miso Soup',
      country: 'Japan',
      region: 'Asia',
      prepTime: '15 mins',
      image: 'https://images.unsplash.com/photo-1623595119708-26b1f7500036?w=500&q=80',
      isFavorite: false,
      description: 'Soup with miso, tofu, and seaweed.',
      coordinates: [35.6895, 139.6917], // Tokyo coordinates
      ingredients: ['Miso paste', 'Tofu', 'Wakame seaweed', 'Green onion', 'Dashi'],
      instructions: ['Heat dashi', 'Add miso', 'Add tofu and seaweed', 'Serve'],
      dietaryTags: ['vegetarian'],
    },
    {
      id: 'mock-508',
      title: 'Gyoza (Dumplings)',
      country: 'Japan',
      region: 'Asia',
      prepTime: '50 mins',
      image: 'https://images.unsplash.com/photo-1632707994633-41217923fb55?w=500&q=80',
      isFavorite: false,
      description: 'Pan-fried dumplings with pork and cabbage filling.',
      coordinates: [35.6895, 139.6917], // Tokyo coordinates
      ingredients: ['Gyoza wrappers', 'Pork', 'Cabbage', 'Garlic', 'Ginger'],
      instructions: ['Make filling', 'Wrap dumplings', 'Pan-fry', 'Steam'],
      dietaryTags: [],
    },
    {
      id: 'mock-509',
      title: 'Unagi Don (Grilled Eel Rice Bowl)',
      country: 'Japan',
      region: 'Asia',
      prepTime: '45 mins',
      image: 'https://images.unsplash.com/photo-1569050939896-2dec76108028?w=500&q=80',
      isFavorite: false,
      description: 'Grilled eel glazed with sweet soy sauce over rice.',
      coordinates: [34.6937, 135.5023], // Osaka coordinates
      ingredients: ['Eel fillets', 'Rice', 'Soy sauce', 'Sugar', 'Mirin'],
      instructions: ['Grill eel', 'Brush with sauce', 'Serve over rice'],
      dietaryTags: [],
    },
    {
      id: 'mock-510',
      title: 'Matcha Mochi',
      country: 'Japan',
      region: 'Asia',
      prepTime: '30 mins',
      image: 'https://images.unsplash.com/photo-1587314168485-3236d6710969?w=500&q=80',
      isFavorite: false,
      description: 'Sweet rice cakes flavored with matcha green tea.',
      coordinates: [35.0116, 135.7681], // Kyoto coordinates
      ingredients: ['Glutinous rice flour', 'Sugar', 'Matcha powder', 'Red bean paste'],
      instructions: ['Mix dough', 'Steam', 'Shape and fill with bean paste'],
      dietaryTags: ['vegan'],
    }
  ],
  'Thai': [
    {
      id: 'mock-601',
      title: 'Pad Thai',
      country: 'Thailand',
      region: 'Asia',
      prepTime: '30 mins',
      image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=500&q=80',
      isFavorite: false,
      description: 'Stir-fried rice noodles with shrimp, tofu, and peanuts.',
      coordinates: [13.7563, 100.5018], // Bangkok coordinates
      ingredients: ['Rice noodles', 'Shrimp', 'Tofu', 'Egg', 'Tamarind', 'Peanuts'],
      instructions: ['Soak noodles', 'Stir-fry ingredients', 'Add sauce', 'Garnish with peanuts'],
      dietaryTags: [],
    },
    {
      id: 'mock-602',
      title: 'Tom Yum Goong',
      country: 'Thailand',
      region: 'Asia',
      prepTime: '35 mins',
      image: 'https://images.unsplash.com/photo-1548943487-a2e4e43b4853?w=500&q=80',
      isFavorite: false,
      description: 'Spicy and sour shrimp soup with lemongrass.',
      coordinates: [13.7563, 100.5018], // Bangkok coordinates
      ingredients: ['Shrimp', 'Lemongrass', 'Kaffir lime leaves', 'Galangal', 'Chili', 'Mushrooms'],
      instructions: ['Boil broth', 'Add aromatics', 'Add shrimp and mushrooms', 'Season'],
      dietaryTags: ['gluten-free'],
    },
    {
      id: 'mock-603',
      title: 'Green Curry',
      country: 'Thailand',
      region: 'Asia',
      prepTime: '40 mins',
      image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=500&q=80',
      isFavorite: false,
      description: 'Spicy coconut curry with chicken and vegetables.',
      coordinates: [13.7563, 100.5018], // Bangkok coordinates
      ingredients: ['Chicken', 'Green curry paste', 'Coconut milk', 'Eggplant', 'Basil'],
      instructions: ['Cook curry paste', 'Add coconut milk', 'Add chicken and veggies', 'Simmer'],
      dietaryTags: ['gluten-free'],
    },
    {
      id: 'mock-604',
      title: 'Som Tum (Papaya Salad)',
      country: 'Thailand',
      region: 'Asia',
      prepTime: '20 mins',
      image: 'https://images.unsplash.com/photo-1626804475297-41608ea09aeb?w=500&q=80',
      isFavorite: false,
      description: 'Shredded green papaya salad with chili and lime.',
      coordinates: [13.7563, 100.5018], // Bangkok coordinates
      ingredients: ['Green papaya', 'Tomato', 'Green beans', 'Peanuts', 'Fish sauce', 'Lime'],
      instructions: ['Shred papaya', 'Pound with other ingredients', 'Serve'],
      dietaryTags: ['gluten-free'],
    },
    {
      id: 'mock-605',
      title: 'Massaman Curry',
      country: 'Thailand',
      region: 'Asia',
      prepTime: '1 hr',
      image: 'https://images.unsplash.com/photo-1569562211093-4bd31d95603a?w=500&q=80',
      isFavorite: false,
      description: 'Rich curry with beef, potatoes, and peanuts.',
      coordinates: [13.7563, 100.5018], // Bangkok coordinates
      ingredients: ['Beef', 'Massaman curry paste', 'Potatoes', 'Coconut milk', 'Peanuts'],
      instructions: ['Brown beef', 'Add paste and coconut milk', 'Simmer with potatoes'],
      dietaryTags: ['gluten-free'],
    },
    {
      id: 'mock-606',
      title: 'Panang Curry',
      country: 'Thailand',
      region: 'Asia',
      prepTime: '40 mins',
      image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=500&q=80',
      isFavorite: false,
      description: 'Mild coconut curry with chicken or tofu.',
      coordinates: [13.7563, 100.5018], // Bangkok coordinates
      ingredients: ['Chicken or tofu', 'Panang curry paste', 'Coconut milk', 'Bell pepper', 'Basil'],
      instructions: ['Cook paste', 'Add coconut milk', 'Add protein and veggies', 'Simmer'],
      dietaryTags: ['gluten-free'],
    },
    {
      id: 'mock-607',
      title: 'Pad Kra Pao (Basil Chicken)',
      country: 'Thailand',
      region: 'Asia',
      prepTime: '25 mins',
      image: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=500&q=80',
      isFavorite: false,
      description: 'Spicy stir-fried chicken with holy basil.',
      coordinates: [13.7563, 100.5018], // Bangkok coordinates
      ingredients: ['Chicken', 'Holy basil', 'Chili', 'Garlic', 'Soy sauce'],
      instructions: ['Stir-fry chicken', 'Add basil and sauce', 'Serve with rice'],
      dietaryTags: [],
    },
    {
      id: 'mock-608',
      title: 'Mango Sticky Rice',
      country: 'Thailand',
      region: 'Asia',
      prepTime: '30 mins',
      image: 'https://images.unsplash.com/photo-1581184953963-d15972933db1?w=500&q=80',
      isFavorite: false,
      description: 'Sweet sticky rice with coconut milk and mango.',
      coordinates: [13.7563, 100.5018], // Bangkok coordinates
      ingredients: ['Glutinous rice', 'Coconut milk', 'Sugar', 'Mango', 'Salt'],
      instructions: ['Cook rice', 'Mix with coconut milk', 'Serve with mango'],
      dietaryTags: ['vegan'],
    },
    {
      id: 'mock-609',
      title: 'Larb',
      country: 'Thailand',
      region: 'Asia',
      prepTime: '25 mins',
      image: 'https://images.unsplash.com/photo-1621451464444-c19eac376fcc?w=500&q=80',
      isFavorite: false,
      description: 'Spicy minced meat salad with herbs and lime.',
      coordinates: [17.9642, 102.6130], // Laos border region coordinates
      ingredients: ['Ground pork or chicken', 'Shallots', 'Mint', 'Lime', 'Fish sauce', 'Chili'],
      instructions: ['Cook meat', 'Mix with herbs and dressing', 'Serve'],
      dietaryTags: ['gluten-free'],
    },
    {
      id: 'mock-610',
      title: 'Thai Spring Rolls',
      country: 'Thailand',
      region: 'Asia',
      prepTime: '35 mins',
      image: 'https://images.unsplash.com/photo-1582836008901-91bf93ee04b5?w=500&q=80',
      isFavorite: false,
      description: 'Crispy rolls with vegetables and glass noodles.',
      coordinates: [13.7563, 100.5018], // Bangkok coordinates
      ingredients: ['Spring roll wrappers', 'Cabbage', 'Carrot', 'Glass noodles', 'Soy sauce'],
      instructions: ['Prepare filling', 'Wrap', 'Fry until golden'],
      dietaryTags: ['vegan'],
    }
  ],
  'French': [
    {
      id: 'mock-701',
      title: 'Coq au Vin',
      country: 'France',
      region: 'Europe',
      prepTime: '2 hrs',
      image: 'https://images.unsplash.com/photo-1600891963935-9a67153146ee?w=500&q=80',
      isFavorite: false,
      description: 'Chicken braised in red wine with mushrooms and bacon.',
      coordinates: [48.8566, 2.3522], // Paris coordinates
      ingredients: ['Chicken', 'Red wine', 'Mushrooms', 'Bacon', 'Onion', 'Carrot'],
      instructions: ['Brown chicken', 'Add wine and veggies', 'Simmer until tender'],
      dietaryTags: [],
    },
    {
      id: 'mock-702',
      title: 'Ratatouille',
      country: 'France',
      region: 'Europe',
      prepTime: '1 hr',
      image: 'https://images.unsplash.com/photo-1572453800999-e8d2d1589b7c?w=500&q=80',
      isFavorite: false,
      description: 'Provençal vegetable stew with eggplant, zucchini, and peppers.',
      coordinates: [43.6047, 1.4442], // Toulouse coordinates
      ingredients: ['Eggplant', 'Zucchini', 'Bell pepper', 'Tomato', 'Onion', 'Herbs'],
      instructions: ['Slice veggies', 'Layer in dish', 'Bake until tender'],
      dietaryTags: ['vegan'],
    },
    {
      id: 'mock-703',
      title: 'Quiche Lorraine',
      country: 'France',
      region: 'Europe',
      prepTime: '1 hr',
      image: 'https://images.unsplash.com/photo-1559717201-2879521b49f4?w=500&q=80',
      isFavorite: false,
      description: 'Savory tart with bacon, cheese, and custard filling.',
      coordinates: [48.6921, 6.1844], // Nancy coordinates
      ingredients: ['Pie crust', 'Bacon', 'Eggs', 'Cream', 'Gruyère cheese'],
      instructions: ['Prepare crust', 'Mix filling', 'Bake until set'],
      dietaryTags: [],
    },
    {
      id: 'mock-704',
      title: 'Bouillabaisse',
      country: 'France',
      region: 'Europe',
      prepTime: '1 hr 30 mins',
      image: 'https://images.unsplash.com/photo-1614526261139-1e5b11a007f3?w=500&q=80',
      isFavorite: false,
      description: 'Provencal fish stew with saffron and vegetables.',
      coordinates: [43.2965, 5.3698], // Marseille coordinates
      ingredients: ['Mixed fish', 'Shellfish', 'Tomato', 'Fennel', 'Saffron', 'Garlic'],
      instructions: ['Simmer broth', 'Add seafood', 'Serve with rouille'],
      dietaryTags: ['gluten-free'],
    },
    {
      id: 'mock-705',
      title: 'Croque Monsieur',
      country: 'France',
      region: 'Europe',
      prepTime: '30 mins',
      image: 'https://images.unsplash.com/photo-1624958024789-5510d2973b9a?w=500&q=80',
      isFavorite: false,
      description: 'Grilled ham and cheese sandwich with béchamel.',
      coordinates: [48.8566, 2.3522], // Paris coordinates
      ingredients: ['Bread', 'Ham', 'Gruyère', 'Béchamel sauce', 'Butter'],
      instructions: ['Assemble sandwich', 'Top with sauce', 'Broil'],
      dietaryTags: [],
    },
    {
      id: 'mock-706',
      title: 'Duck à l\'Orange',
      country: 'France',
      region: 'Europe',
      prepTime: '2 hrs',
      image: 'https://images.unsplash.com/photo-1617471241260-846e6e325246?w=500&q=80',
      isFavorite: false,
      description: 'Roast duck with orange sauce.',
      coordinates: [48.8566, 2.3522], // Paris coordinates
      ingredients: ['Duck', 'Oranges', 'Sugar', 'Vinegar', 'Stock'],
      instructions: ['Roast duck', 'Prepare orange sauce', 'Serve together'],
      dietaryTags: ['gluten-free'],
    },
    {
      id: 'mock-707',
      title: 'Tarte Tatin',
      country: 'France',
      region: 'Europe',
      prepTime: '1 hr',
      image: 'https://images.unsplash.com/photo-1631206753348-db44968fd440?w=500&q=80',
      isFavorite: false,
      description: 'Upside-down caramelized apple tart.',
      coordinates: [47.3900, 0.6889], // Loire Valley coordinates
      ingredients: ['Apples', 'Sugar', 'Butter', 'Pastry dough'],
      instructions: ['Caramelize apples', 'Top with dough', 'Bake', 'Invert to serve'],
      dietaryTags: ['vegetarian'],
    },
    {
      id: 'mock-708',
      title: 'French Onion Soup',
      country: 'France',
      region: 'Europe',
      prepTime: '1 hr',
      image: 'https://images.unsplash.com/photo-1583394810336-c1cadd3b3acd?w=500&q=80',
      isFavorite: false,
      description: 'Caramelized onion soup with cheese-topped bread.',
      coordinates: [48.8566, 2.3522], // Paris coordinates
      ingredients: ['Onions', 'Beef broth', 'Bread', 'Gruyère', 'Butter'],
      instructions: ['Caramelize onions', 'Simmer in broth', 'Top with bread and cheese', 'Broil'],
      dietaryTags: ['vegetarian'],
    },
    {
      id: 'mock-709',
      title: 'Crêpes Suzette',
      country: 'France',
      region: 'Europe',
      prepTime: '30 mins',
      image: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=500&q=80',
      isFavorite: false,
      description: 'Thin pancakes with orange liqueur sauce.',
      coordinates: [48.8566, 2.3522], // Paris coordinates
      ingredients: ['Flour', 'Eggs', 'Milk', 'Butter', 'Orange liqueur', 'Sugar'],
      instructions: ['Make crêpes', 'Prepare sauce', 'Flambé and serve'],
      dietaryTags: ['vegetarian'],
    },
    {
      id: 'mock-710',
      title: 'Madeleines',
      country: 'France',
      region: 'Europe',
      prepTime: '35 mins',
      image: 'https://images.unsplash.com/photo-1587227613214-eb57a9d7b7e2?w=500&q=80',
      isFavorite: false,
      description: 'Small shell-shaped sponge cakes.',
      coordinates: [49.1193, 6.1757], // Metz coordinates
      ingredients: ['Flour', 'Eggs', 'Sugar', 'Butter', 'Lemon zest'],
      instructions: ['Mix batter', 'Fill molds', 'Bake'],
      dietaryTags: ['vegetarian'],
    }
  ],
  'American': [
    {
      id: 'mock-801',
      title: 'Classic Burger',
      country: 'USA',
      region: 'North America',
      prepTime: '30 mins',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&q=80',
      isFavorite: false,
      description: 'Grilled beef patty on a bun with toppings.',
      coordinates: [40.7128, -74.0060], // New York coordinates
      ingredients: ['Ground beef', 'Buns', 'Lettuce', 'Tomato', 'Cheese', 'Pickles'],
      instructions: ['Shape patties', 'Grill', 'Assemble with toppings'],
      dietaryTags: [],
    },
    {
      id: 'mock-802',
      title: 'Buffalo Wings',
      country: 'USA',
      region: 'North America',
      prepTime: '45 mins',
      image: 'https://images.unsplash.com/photo-1608039755401-742074f0548d?w=500&q=80',
      isFavorite: false,
      description: 'Fried chicken wings tossed in hot sauce.',
      coordinates: [42.8864, -78.8784], // Buffalo coordinates
      ingredients: ['Chicken wings', 'Hot sauce', 'Butter', 'Celery', 'Blue cheese'],
      instructions: ['Fry wings', 'Toss in sauce', 'Serve with celery'],
      dietaryTags: [],
    },
    {
      id: 'mock-803',
      title: 'Macaroni and Cheese',
      country: 'USA',
      region: 'North America',
      prepTime: '40 mins',
      image: 'https://images.unsplash.com/photo-1543339494-b4cd1c86e4f0?w=500&q=80',
      isFavorite: false,
      description: 'Baked pasta with creamy cheese sauce.',
      coordinates: [42.3601, -71.0589], // Boston coordinates
      ingredients: ['Macaroni', 'Cheddar cheese', 'Milk', 'Butter', 'Flour'],
      instructions: ['Cook pasta', 'Make cheese sauce', 'Mix and bake'],
      dietaryTags: ['vegetarian'],
    },
    {
      id: 'mock-804',
      title: 'Clam Chowder',
      country: 'USA',
      region: 'North America',
      prepTime: '1 hr',
      image: 'https://images.unsplash.com/photo-1566454825481-9c03f1eff9c7?w=500&q=80',
      isFavorite: false,
      description: 'Creamy soup with clams, potatoes, and bacon.',
      coordinates: [42.3601, -71.0589], // Boston coordinates
      ingredients: ['Clams', 'Potatoes', 'Bacon', 'Onion', 'Cream'],
      instructions: ['Cook bacon', 'Add veggies and clams', 'Simmer with cream'],
      dietaryTags: ['gluten-free'],
    },
    {
      id: 'mock-805',
      title: 'Cobb Salad',
      country: 'USA',
      region: 'North America',
      prepTime: '30 mins',
      image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500&q=80',
      isFavorite: false,
      description: 'Salad with chicken, bacon, blue cheese, and avocado.',
      coordinates: [34.0522, -118.2437], // Los Angeles coordinates
      ingredients: ['Chicken', 'Bacon', 'Egg', 'Blue cheese', 'Avocado', 'Lettuce'],
      instructions: ['Cook chicken and bacon', 'Chop ingredients', 'Assemble salad'],
      dietaryTags: ['gluten-free'],
    },
    {
      id: 'mock-806',
      title: 'Southern Fried Chicken',
      country: 'USA',
      region: 'North America',
      prepTime: '1 hr',
      image: 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=500&q=80',
      isFavorite: false,
      description: 'Crispy fried chicken with seasoned coating.',
      coordinates: [33.7490, -84.3880], // Atlanta coordinates
      ingredients: ['Chicken', 'Flour', 'Buttermilk', 'Spices', 'Oil'],
      instructions: ['Soak chicken', 'Coat in flour', 'Fry until golden'],
      dietaryTags: [],
    },
    {
      id: 'mock-807',
      title: 'New York Cheesecake',
      country: 'USA',
      region: 'North America',
      prepTime: '1 hr 30 mins',
      image: 'https://images.unsplash.com/photo-1524351199678-941a58a3df40?w=500&q=80',
      isFavorite: false,
      description: 'Rich baked cheesecake with graham crust.',
      coordinates: [40.7128, -74.0060], // New York coordinates
      ingredients: ['Cream cheese', 'Sugar', 'Eggs', 'Graham crackers', 'Butter'],
      instructions: ['Make crust', 'Mix filling', 'Bake', 'Chill'],
      dietaryTags: ['vegetarian'],
    },
    {
      id: 'mock-808',
      title: 'BBQ Ribs',
      country: 'USA',
      region: 'North America',
      prepTime: '2 hrs',
      image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=500&q=80',
      isFavorite: false,
      description: 'Slow-cooked pork ribs with barbecue sauce.',
      coordinates: [35.1495, -90.0490], // Memphis coordinates
      ingredients: ['Pork ribs', 'BBQ sauce', 'Spices', 'Brown sugar'],
      instructions: ['Season ribs', 'Slow cook', 'Baste with sauce'],
      dietaryTags: ['gluten-free'],
    },
    {
      id: 'mock-809',
      title: 'Jambalaya',
      country: 'USA',
      region: 'North America',
      prepTime: '1 hr',
      image: 'https://images.unsplash.com/photo-1547592180-7a6416bd7e56?w=500&q=80',
      isFavorite: false,
      description: 'Spicy rice dish with sausage, chicken, and shrimp.',
      coordinates: [29.9511, -90.0715], // New Orleans coordinates
      ingredients: ['Rice', 'Sausage', 'Chicken', 'Shrimp', 'Bell pepper', 'Tomato'],
      instructions: ['Cook meats', 'Add rice and veggies', 'Simmer'],
      dietaryTags: ['gluten-free'],
    },
    {
      id: 'mock-810',
      title: 'Pumpkin Pie',
      country: 'USA',
      region: 'North America',
      prepTime: '1 hr',
      image: 'https://images.unsplash.com/photo-1509461399763-ae67a981b254?w=500&q=80',
      isFavorite: false,
      description: 'Spiced pumpkin custard pie.',
      coordinates: [39.7392, -104.9903], // Denver coordinates
      ingredients: ['Pumpkin puree', 'Pie crust', 'Eggs', 'Sugar', 'Spices'],
      instructions: ['Mix filling', 'Pour into crust', 'Bake'],
      dietaryTags: ['vegetarian'],
    }
  ],
  'Spanish': [
    {
      id: 'mock-901',
      title: 'Authentic Paella',
      country: 'Spain',
      region: 'Europe',
      prepTime: '1 hr 30 mins',
      image: 'https://images.unsplash.com/photo-1515443961218-a51367888e4b?w=500&q=80',
      isFavorite: false,
      description: 'Traditional Valencian rice dish with saffron and various meats.',
      coordinates: [39.4699, -0.3763], // Valencia coordinates
      ingredients: ['Bomba rice', 'Saffron', 'Chicken', 'Rabbit', 'Bell peppers', 'Tomatoes', 'Green beans', 'Olive oil'],
      instructions: ['Sauté meat until golden', 'Add vegetables and cook briefly', 'Add rice and saffron-infused broth', 'Cook without stirring until rice is done', 'Rest before serving'],
      dietaryTags: ['dairy-free'],
    },
    {
      id: 'mock-902',
      title: 'Tortilla Española',
      country: 'Spain',
      region: 'Europe',
      prepTime: '45 mins',
      image: 'https://images.unsplash.com/photo-1607118750647-2295968a4c1d?w=500&q=80',
      isFavorite: false,
      description: 'Classic Spanish potato omelette, a staple in Spanish cuisine.',
      coordinates: [40.4168, -3.7038], // Madrid coordinates
      ingredients: ['Potatoes', 'Eggs', 'Onion', 'Olive oil', 'Salt'],
      instructions: ['Slice potatoes and onions thinly', 'Fry in olive oil until tender', 'Mix with beaten eggs', 'Cook slowly, flipping halfway'],
      dietaryTags: ['vegetarian', 'gluten-free'],
    },
    {
      id: 'mock-903',
      title: 'Gazpacho',
      country: 'Spain',
      region: 'Europe',
      prepTime: '20 mins + chilling',
      image: 'https://images.unsplash.com/photo-1603105037243-339466a55ff0?w=500&q=80',
      isFavorite: false,
      description: 'Cold soup made from raw, blended vegetables, perfect for hot days.',
      coordinates: [37.3891, -5.9845], // Seville coordinates
      ingredients: ['Tomatoes', 'Cucumber', 'Bell pepper', 'Garlic', 'Olive oil', 'Vinegar', 'Bread'],
      instructions: ['Blend all ingredients until smooth', 'Season to taste', 'Chill for at least 2 hours', 'Serve cold with toppings'],
      dietaryTags: ['vegetarian', 'dairy-free'],
    },
    {
      id: 'mock-904',
      title: 'Churros con Chocolate',
      country: 'Spain',
      region: 'Europe',
      prepTime: '30 mins',
      image: 'https://images.unsplash.com/photo-1624781310620-2152693a12e4?w=500&q=80',
      isFavorite: false,
      description: 'Fried dough pastries served with thick hot chocolate for dipping.',
      coordinates: [40.4168, -3.7038], // Madrid coordinates
      ingredients: ['Flour', 'Water', 'Salt', 'Oil', 'Dark chocolate', 'Milk', 'Sugar'],
      instructions: ['Prepare dough and pipe into hot oil', 'Fry until golden', 'Drain and dust with sugar', 'Make thick hot chocolate for dipping'],
      dietaryTags: ['vegetarian'],
    },
    {
      id: 'mock-905',
      title: 'Pulpo a la Gallega',
      country: 'Spain',
      region: 'Europe',
      prepTime: '1 hr',
      image: 'https://images.unsplash.com/photo-1632914187965-0bf9b92bda2b?w=500&q=80',
      isFavorite: false,
      description: 'Galician-style octopus with paprika and olive oil.',
      coordinates: [42.8782, -8.5448], // Santiago de Compostela coordinates
      ingredients: ['Octopus', 'Potatoes', 'Olive oil', 'Paprika', 'Salt', 'Bay leaves'],
      instructions: ['Cook octopus in boiling water', 'Slice into pieces', 'Arrange over boiled potatoes', 'Drizzle with olive oil and paprika'],
      dietaryTags: ['gluten-free', 'dairy-free'],
    },
    {
      id: 'mock-906',
      title: 'Patatas Bravas',
      country: 'Spain',
      region: 'Europe',
      prepTime: '40 mins',
      image: 'https://images.unsplash.com/photo-1599308351172-8c140bd278c7?w=500&q=80',
      isFavorite: false,
      description: 'Crispy fried potatoes topped with spicy tomato sauce and aioli.',
      coordinates: [41.3851, 2.1734], // Barcelona coordinates
      ingredients: ['Potatoes', 'Tomato sauce', 'Paprika', 'Garlic', 'Mayonnaise', 'Olive oil'],
      instructions: ['Cube and fry potatoes until crispy', 'Prepare spicy tomato sauce', 'Make garlic aioli', 'Top potatoes with sauces'],
      dietaryTags: ['vegetarian', 'gluten-free'],
    },
    {
      id: 'mock-907',
      title: 'Croquetas',
      country: 'Spain',
      region: 'Europe',
      prepTime: '1 hr + chilling',
      image: 'https://images.unsplash.com/photo-1630175858349-ab6c431a0538?w=500&q=80',
      isFavorite: false,
      description: 'Creamy béchamel fritters with ham or other fillings.',
      coordinates: [40.4168, -3.7038], // Madrid coordinates
      ingredients: ['Butter', 'Flour', 'Milk', 'Ham', 'Breadcrumbs', 'Eggs', 'Oil'],
      instructions: ['Make thick béchamel sauce', 'Add fillings', 'Chill until firm', 'Shape, bread, and fry until golden'],
      dietaryTags: [],
    },
    {
      id: 'mock-908',
      title: 'Gambas al Ajillo',
      country: 'Spain',
      region: 'Europe',
      prepTime: '20 mins',
      image: 'https://images.unsplash.com/photo-1625944230945-1b7dd3b949ab?w=500&q=80',
      isFavorite: false,
      description: 'Garlic shrimp cooked in olive oil and chili.',
      coordinates: [36.7213, -4.4213], // Málaga coordinates
      ingredients: ['Shrimp', 'Garlic', 'Olive oil', 'Chili', 'Parsley', 'Lemon'],
      instructions: ['Heat oil with garlic and chili', 'Add shrimp and cook quickly', 'Finish with parsley and lemon juice', 'Serve immediately with bread'],
      dietaryTags: ['gluten-free', 'dairy-free'],
    },
    {
      id: 'mock-909',
      title: 'Crema Catalana',
      country: 'Spain',
      region: 'Europe',
      prepTime: '30 mins + chilling',
      image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500&q=80',
      isFavorite: false,
      description: 'Catalan custard dessert with caramelized sugar top.',
      coordinates: [41.3851, 2.1734], // Barcelona coordinates
      ingredients: ['Milk', 'Cream', 'Egg yolks', 'Sugar', 'Cornstarch', 'Lemon zest', 'Cinnamon'],
      instructions: ['Cook custard with aromatics', 'Chill in ramekins', 'Top with sugar', 'Caramelize with torch before serving'],
      dietaryTags: ['vegetarian', 'gluten-free'],
    },
    {
      id: 'mock-910',
      title: 'Pimientos de Padrón',
      country: 'Spain',
      region: 'Europe',
      prepTime: '10 mins',
      image: 'https://images.unsplash.com/photo-1601056645442-71c0f9646857?w=500&q=80',
      isFavorite: false,
      description: 'Small green peppers, pan-fried and salted.',
      coordinates: [42.8782, -8.5448], // Santiago de Compostela coordinates
      ingredients: ['Padrón peppers', 'Olive oil', 'Sea salt'],
      instructions: ['Heat oil in pan', 'Fry peppers until blistered', 'Drain and sprinkle with salt', 'Serve immediately as a tapa'],
      dietaryTags: ['vegetarian', 'vegan', 'gluten-free', 'dairy-free'],
    }
  ],
  'Greek': [
    {
      id: 'mock-1001',
      title: 'Greek Salad',
      country: 'Greece',
      region: 'Europe',
      prepTime: '15 mins',
      image: 'https://images.unsplash.com/photo-1551248429-40975aa4de74?w=500&q=80',
      isFavorite: false,
      description: 'Fresh and vibrant salad with tomatoes, cucumber, olives, and feta cheese, dressed with olive oil and oregano.',
      coordinates: [37.9838, 23.7275], // Athens coordinates
      ingredients: ['Tomatoes', 'Cucumber', 'Red onion', 'Feta cheese', 'Kalamata olives', 'Olive oil', 'Red wine vinegar', 'Oregano'],
      instructions: ['Chop vegetables into chunks', 'Add olives', 'Top with feta cheese block', 'Dress with olive oil and vinegar', 'Sprinkle with oregano'],
      dietaryTags: ['vegetarian', 'gluten-free'],
    },
    {
      id: 'mock-1002',
      title: 'Moussaka',
      country: 'Greece',
      region: 'Europe',
      prepTime: '1 hr 30 mins',
      image: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=500&q=80',
      isFavorite: false,
      description: 'Traditional Greek casserole with layers of eggplant, potato, and spiced ground meat topped with béchamel sauce.',
      coordinates: [37.9838, 23.7275], // Athens coordinates
      ingredients: ['Eggplant', 'Potatoes', 'Ground lamb', 'Tomatoes', 'Onion', 'Cinnamon', 'Milk', 'Flour', 'Butter', 'Eggs'],
      instructions: ['Layer sliced eggplant and potatoes', 'Cook meat sauce with spices', 'Make béchamel sauce', 'Layer in baking dish', 'Bake until golden and bubbly'],
      dietaryTags: [],
    },
    {
      id: 'mock-1003',
      title: 'Souvlaki',
      country: 'Greece',
      region: 'Europe',
      prepTime: '30 mins + marinating',
      image: 'https://images.unsplash.com/photo-1604908176997-125f7c9a368c?w=500&q=80',
      isFavorite: false,
      description: 'Grilled skewers of marinated meat served with pita, tzatziki, and vegetables.',
      coordinates: [37.9838, 23.7275], // Athens coordinates
      ingredients: ['Pork or chicken', 'Olive oil', 'Lemon juice', 'Garlic', 'Oregano', 'Pita bread', 'Tzatziki', 'Tomatoes', 'Onions'],
      instructions: ['Marinate meat chunks', 'Thread onto skewers', 'Grill until charred and cooked', 'Serve with warm pita and tzatziki'],
      dietaryTags: ['dairy-free'],
    },
    {
      id: 'mock-1004',
      title: 'Tzatziki',
      country: 'Greece',
      region: 'Europe',
      prepTime: '15 mins + straining',
      image: 'https://images.unsplash.com/photo-1615714849110-851aec33c6c5?w=500&q=80',
      isFavorite: false,
      description: 'Creamy yogurt dip with cucumber, garlic, and herbs.',
      coordinates: [37.9838, 23.7275], // Athens coordinates
      ingredients: ['Greek yogurt', 'Cucumber', 'Garlic', 'Olive oil', 'Lemon juice', 'Dill', 'Mint', 'Salt'],
      instructions: ['Grate and strain cucumber', 'Mix with thick yogurt', 'Add minced garlic and herbs', 'Drizzle with olive oil before serving'],
      dietaryTags: ['vegetarian', 'gluten-free'],
    },
    {
      id: 'mock-1005',
      title: 'Spanakopita',
      country: 'Greece',
      region: 'Europe',
      prepTime: '1 hr',
      image: 'https://images.unsplash.com/photo-1601051294997-200869946b52?w=500&q=80',
      isFavorite: false,
      description: 'Flaky phyllo pastry filled with spinach and feta cheese.',
      coordinates: [37.9838, 23.7275], // Athens coordinates
      ingredients: ['Phyllo dough', 'Spinach', 'Feta cheese', 'Onion', 'Eggs', 'Dill', 'Olive oil', 'Butter'],
      instructions: ['Sauté spinach with onions', 'Mix with feta and herbs', 'Layer phyllo sheets with oil', 'Fill and fold', 'Bake until golden'],
      dietaryTags: ['vegetarian'],
    },
    {
      id: 'mock-1006',
      title: 'Baklava',
      country: 'Greece',
      region: 'Europe',
      prepTime: '1 hr + soaking',
      image: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=500&q=80',
      isFavorite: false,
      description: 'Sweet layered pastry with chopped nuts and honey syrup.',
      coordinates: [37.9838, 23.7275], // Athens coordinates
      ingredients: ['Phyllo dough', 'Walnuts', 'Almonds', 'Cinnamon', 'Cloves', 'Butter', 'Honey', 'Sugar', 'Lemon'],
      instructions: ['Layer buttered phyllo sheets', 'Add nut mixture between layers', 'Cut before baking', 'Pour honey syrup over hot pastry', 'Let soak before serving'],
      dietaryTags: ['vegetarian'],
    },
    {
      id: 'mock-1007',
      title: 'Pastitsio',
      country: 'Greece',
      region: 'Europe',
      prepTime: '1 hr 15 mins',
      image: 'https://images.unsplash.com/photo-1605548380196-68da0d91d753?w=500&q=80',
      isFavorite: false,
      description: 'Greek pasta bake with ground meat and béchamel sauce.',
      coordinates: [37.9838, 23.7275], // Athens coordinates
      ingredients: ['Pasta tubes', 'Ground beef', 'Tomato sauce', 'Onion', 'Cinnamon', 'Nutmeg', 'Milk', 'Flour', 'Butter', 'Cheese'],
      instructions: ['Cook pasta', 'Prepare meat sauce', 'Make béchamel', 'Layer in baking dish', 'Bake until golden'],
      dietaryTags: [],
    },
    {
      id: 'mock-1008',
      title: 'Dolmades',
      country: 'Greece',
      region: 'Europe',
      prepTime: '45 mins',
      image: 'https://images.unsplash.com/photo-1611545417328-742c526736b5?w=500&q=80',
      isFavorite: false,
      description: 'Stuffed grape leaves with rice, herbs, and sometimes meat.',
      coordinates: [37.9838, 23.7275], // Athens coordinates
      ingredients: ['Grape leaves', 'Rice', 'Onion', 'Mint', 'Dill', 'Parsley', 'Lemon', 'Olive oil', 'Pine nuts'],
      instructions: ['Prepare rice filling with herbs', 'Place filling on grape leaves', 'Roll tightly', 'Simmer in lemon broth until tender'],
      dietaryTags: ['vegetarian', 'gluten-free', 'dairy-free'],
    },
    {
      id: 'mock-1009',
      title: 'Galaktoboureko',
      country: 'Greece',
      region: 'Europe',
      prepTime: '1 hr',
      image: 'https://images.unsplash.com/photo-1619985632461-f0d773af6bed?w=500&q=80',
      isFavorite: false,
      description: 'Custard-filled phyllo pastry soaked in sweet syrup.',
      coordinates: [37.9838, 23.7275], // Athens coordinates
      ingredients: ['Phyllo dough', 'Milk', 'Semolina', 'Eggs', 'Sugar', 'Vanilla', 'Butter', 'Lemon', 'Cinnamon'],
      instructions: ['Make custard with semolina', 'Layer phyllo sheets with butter', 'Pour custard in center', 'Fold and bake', 'Drizzle with syrup while hot'],
      dietaryTags: ['vegetarian'],
    },
    {
      id: 'mock-1010',
      title: 'Avgolemono Soup',
      country: 'Greece',
      region: 'Europe',
      prepTime: '45 mins',
      image: 'https://images.unsplash.com/photo-1547592180-6307a6733783?w=500&q=80',
      isFavorite: false,
      description: 'Creamy lemon and egg soup with rice or orzo pasta.',
      coordinates: [37.9838, 23.7275], // Athens coordinates
      ingredients: ['Chicken broth', 'Rice or orzo', 'Eggs', 'Lemons', 'Chicken', 'Onion', 'Celery', 'Carrots', 'Dill'],
      instructions: ['Cook rice in broth', 'Temper eggs with lemon juice', 'Slowly incorporate into hot broth', 'Stir until thickened', 'Add cooked chicken if desired'],
      dietaryTags: ['gluten-free'],
    }
  ]
};

// Function to get all mock recipes as a flat array
export const getAllMockRecipes = (): Recipe[] => {
  return Object.values(mockRecipesByCuisine).flat();
};

// Function to get mock recipes for a specific cuisine
export const getMockRecipesForCuisine = (cuisine: string): Recipe[] => {
  return mockRecipesByCuisine[cuisine] || [];
};
